### ISSUE TITLE
Receiving only zero values

### ISSUE THREAD

**Issue by sk-lundi** [in-famous-raccoon/proxmox-snmp#6]
![grafik](https://user-images.githubusercontent.com/122994850/213202864-5789f70d-5488-409c-8041-179473548236.png)

Sensor is working fine but only shows 0 on the Sensor

**Comment by in-famous-raccoon** [comment]
Then you don't have a sensor for zone2
try this commands to find the right sensor:
cat /sys/class/thermal/thermal_zone*/type
cat /sys/class/thermal/thermal_zone*/temp

**Comment by aviech** [comment]
Heya, got the same problem here. it's a fujitsu dual socket server, if that matters. when i run
cat /sys/class/thermal/thermal_zone0/temp or cat /sys/class/thermal/thermal_zone1/temp i'll get the temps just fine, cat /sys/class/thermal/thermal_zone*/type returns x86_pkg_temp. But where do i need to change these values in your scripts? 
thanks in advance!

**Comment by in-famous-raccoon** [comment]
Hey,

Just edit line 6 in the file snmp-cpu-temp.sh

**Comment by aviech** [comment]
Hey,

yeah i tried that, still getting a "null2" back...see screenshot.

![image](https://user-images.githubusercontent.com/109900294/217960077-9aa52947-def9-4055-96ba-738ac85eeab7.png)

is the system output maybe in the wrong format? Seems to me like there are some zeros too much

![image](https://user-images.githubusercontent.com/109900294/217960329-afc798ea-e3f8-4c52-aa49-e16b407e1edb.png)

Thanks and Cheers!

**Comment by in-famous-raccoon** [comment]
Hi,

an your snmp-cpu-temp.sh looks like this, with **/sys/class/thermal/thermal_zone1/temp** and **.1.3.6.1.2.1.25.1.8**?

```#!/bin/bash
if [ "$1" = "-g" ]
then
echo .1.3.6.1.2.1.25.1.8
echo gauge
echo `cat /sys/class/thermal/thermal_zone1/temp | sed 's/\(.\)..$/.\1/'`
fi
exit 0
```

**Comment by aviech** [comment]
i've found my mistake, queried the wrong OID....sorry for that and thanks for the help! works fine now!

**Comment by in-famous-raccoon** [comment]
no problem :smile:
